services:
  django:
    build:
      context: .
      dockerfile: ./deployment/django/Dockerfile
    image: {{ cookiecutter.project_slug }}:{{ cookiecutter.version }}
    volumes:
      - production_django_media:/app/{{ cookiecutter.project_slug }}/media
    env_file:
      - ./deployment/django/.env
    depends_on:
      - mysql
    command: /start

  mysql:
    image: mysql:{{ cookiecutter.mysql_version }}
    container_name: mysql
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - "mysql_vol:/var/lib/mysql/"
      - "./deployment/database/init.db:/docker-entrypoint-initdb.d/"
    env_file:
      - "./deployment/database/.env"
    restart: on-failure
  {% if cookiecutter.use_nginx_proxy == 'y' %}

  nginx:
    image:
    depends_on:
      - django
    volumes:
      - ./deployment/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - production_django_media:/usr/share/nginx/media:ro
  {% endif %}
