#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

python << END
import sys
import time

import MySQLdb

suggest_unrecoverable_after = 30
start = time.time()

while True:
    try:
        MySQLdb.connect(
            host="${DJANGO_DB__HOST}",
            port="${DJANGO_DB__PORT}",
            user="${DJANGO_DB__USER}",
            password="${DJANGO_DB__PASSWORD}",
            database="${DJANGO_DB__NAME}"
        )
        break
    except MySQLdb.OperationalError as error:
        sys.stderr.write("Waiting for MySQL to become available...\n")

        if time.time() - start > suggest_unrecoverable_after:
            sys.stderr.write("  This is taking longer than expected. The following exception may be indicative of an unrecoverable error: '{}'\n".format(error))

    time.sleep(1)
END

>&2 echo 'MySQL is available'

exec "$@"
